// Controller adapter: in-memory, single-process store for two pieces of short-lived OAuth flow
// state. This is impure/mutable infrastructure coordination, not business logic — it belongs in
// the Controller layer (which "combines I/O + config to create domain-specific operations", per
// backend-standards), not in Model (must stay pure) and not in Operator (Operator only knows
// generic I/O, no domain knowledge — this store's second responsibility, described below, is
// unavoidably Google-Ads-specific).
//
// It backs two things used by the Model use-cases (via Dependencies):
//
//  1. CSRF `state` tokens: generated by startOAuthFlow, validated+consumed exactly once by
//     handleOAuthCallback (FR1, Security Considerations > CSRF).
//
//  2. The callback→connect token handoff: tokens exchanged during handleOAuthCallback, stashed
//     here keyed by Google Ads `customer_id` (not by `state` or a session id), until
//     connectAccounts consumes and clears them.
//
// Design decision — why keyed by customer_id, and why not in the response body at all:
// The OpenAPI contract for this change (frozen in Phase 2, contracts/ads-manager-api/openapi.yaml)
// does not carry any session/handoff identifier through OAuthCallbackResponse or
// ConnectAccountsRequest — the latter accepts only `customer_ids`. Widening the contract just to
// thread an internal implementation detail through the client felt worse than the alternative:
// one Google identity's refresh token grants access to every customer_id ListAccessibleCustomers
// returned for it (including every MCC sub-account), so the SAME tokens apply to every accessible
// customer_id. Keying the pending-tokens store by customer_id lets connectAccounts look everything
// up directly from the customer_ids it already receives — zero contract changes, and the tokens
// never leave the server (Security Considerations: "toda chamada... ocorre exclusivamente no
// ads-manager-server").
//
// Tradeoffs accepted (documented, not hidden):
//  - If two OAuth flows are started before either is confirmed, and both surface an overlapping
//    customer_id, the second callback's tokens silently win for that customer_id. Acceptable only
//    because this is an explicitly single-user, local, no-concurrent-users app (SPEC.md).
//  - Nothing here survives a process restart, and it does not work across multiple server
//    instances. If this app ever grows a real session layer or scales beyond one instance, this
//    must move to a shared store (e.g. Redis) — out of scope today per the epic's single-user/
//    local-deploy decision.
//  - Uses a plain mutable `Map` directly (`.set`/`.delete`/`.has`), same as the existing
//    `operator/state_machine.ts`'s `listeners: Set`. The typescript-standards immutability rules
//    target domain/business data (Model layer); this is process-local infrastructure bookkeeping,
//    analogous to a DB connection pool's internal state.
import { randomUUID } from 'node:crypto';
import type { PendingCustomerTokens } from '../../model';

const STATE_TTL_MS = 10 * 60 * 1000; // 10 minutes — short-lived, single-use CSRF token
const PENDING_TOKENS_TTL_MS = 10 * 60 * 1000; // matches the time a user reasonably takes to pick accounts

export type OAuthSessionStore = Readonly<{
  readonly generateState: () => string;
  readonly saveState: (state: string) => void;
  readonly consumeState: (state: string | undefined) => boolean;
  readonly savePendingTokens: (customerId: string, tokens: PendingCustomerTokens) => void;
  readonly getPendingTokens: (customerId: string) => PendingCustomerTokens | undefined;
  readonly clearPendingTokens: (customerId: string) => void;
}>;

export const createOAuthSessionStore = (): OAuthSessionStore => {
  const states = new Map<string, number>(); // state -> createdAt (ms)
  const pendingTokens = new Map<string, { readonly value: PendingCustomerTokens; readonly createdAt: number }>();

  const isExpired = (createdAt: number, ttlMs: number): boolean => Date.now() - createdAt >= ttlMs;

  const generateState = (): string => randomUUID();

  const saveState = (state: string): void => {
    states.set(state, Date.now());
  };

  const consumeState = (state: string | undefined): boolean => {
    if (!state) {
      return false;
    }
    const createdAt = states.get(state);
    if (createdAt === undefined) {
      return false;
    }
    states.delete(state); // single-use regardless of outcome
    return !isExpired(createdAt, STATE_TTL_MS);
  };

  const savePendingTokens = (customerId: string, tokens: PendingCustomerTokens): void => {
    pendingTokens.set(customerId, { value: tokens, createdAt: Date.now() });
  };

  const getPendingTokens = (customerId: string): PendingCustomerTokens | undefined => {
    const entry = pendingTokens.get(customerId);
    if (!entry) {
      return undefined;
    }
    if (isExpired(entry.createdAt, PENDING_TOKENS_TTL_MS)) {
      pendingTokens.delete(customerId);
      return undefined;
    }
    return entry.value;
  };

  const clearPendingTokens = (customerId: string): void => {
    pendingTokens.delete(customerId);
  };

  return { generateState, saveState, consumeState, savePendingTokens, getPendingTokens, clearPendingTokens };
};
