-- Seed: 001_seed_data
-- Description: Initial seed data for ads-manager
-- Created: 2026-08-15
--
-- No seed data is defined for this change (google-ads-connection).
-- `connected_accounts` rows are created exclusively through the OAuth connection
-- flow (real Google Ads accounts + encrypted tokens) — there is no static/lookup
-- data to seed, and fabricating fake connected accounts here would be misleading
-- for local development. Add seed files here if a future change introduces
-- lookup/reference data that benefits from one.
